### ISSUE TITLE
after update start this problem

### ISSUE THREAD

**Issue by csgentr** [babofitos/node-steamid-converter#5]
after cs:go update the bot giving me this error..

/home/server-redirect-node-steam-bot/node_modules/steamidconvert/index.js:80
      throw err
      ^

Error: Invalid SteamID
    at SteamConvert.convertTo64 (/home/server-redirect-node-steam-bot/node_modules/steamidconvert/index.js:70:13)
    at Carrier.<anonymous> (/home/server-redirect-node-steam-bot/app.js:147:26)
    at emitOne (events.js:77:13)
    at Carrier.emit (events.js:169:7)
    at /home/server-redirect-node-steam-bot/node_modules/carrier/lib/carrier.js:24:12
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by babofitos** [comment]
what is the steamid that you're trying to convert?
